import jsPDF from 'jspdf';
import type { CalculationResults } from './calculations';

const formatNumber = (value: number): string => {
  return value.toLocaleString(undefined, { 
    minimumFractionDigits: 2,
    maximumFractionDigits: 2 
  });
};

export const generatePDF = (results: CalculationResults, isMetric: boolean) => {
  const doc = new jsPDF();
  
  // Add Poppins font
  doc.setFont("Poppins");
  
  // Title
  doc.setFontSize(20);
  doc.text("SPF Calculator Results", 20, 20);
  
  // Subtitle with current date
  doc.setFontSize(12);
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 30);
  
  // Main Results
  doc.setFontSize(16);
  doc.text("Calculation Results", 20, 45);
  
  doc.setFontSize(12);
  const unit = isMetric ? 'kW/(m³/s)' : 'HP/CFM';
  doc.text(`SPF: ${formatNumber(isMetric ? results.spf : results.spfImperial)} ${unit}`, 20, 55);
  
  // Power and Flow Rate
  doc.text("Power:", 20, 70);
  doc.text(`${formatNumber(results.power.metric)} kW`, 30, 80);
  doc.text(`${formatNumber(results.power.imperial)} HP`, 30, 90);
  
  doc.text("Flow Rate:", 20, 105);
  doc.text(`${formatNumber(results.flow.metric)} m³/s`, 30, 115);
  doc.text(`${formatNumber(results.flow.imperial)} CFM`, 30, 125);
  
  // Pressure Drop Results if available
  if (results.pressureDrop) {
    doc.text("System Analysis", 20, 145);
    doc.text(`Total Pressure Drop: ${formatNumber(results.pressureDrop.totalPressure)} Pa`, 30, 155);
    doc.text(`Fan Efficiency: ${(results.pressureDrop.efficiency * 100).toFixed(1)}%`, 30, 165);
  }
  
  // Guide Section
  doc.addPage();
  doc.setFontSize(16);
  doc.text("SPF Calculator Guide", 20, 20);
  
  doc.setFontSize(12);
  // What is SPF
  doc.text("What is SPF?", 20, 35);
  doc.setFontSize(10);
  const spfText = "Specific Fan Power (SPF) is a measure of fan efficiency that represents the power required " +
                  "to move air through a ventilation system.";
  doc.text(spfText, 20, 45, { maxWidth: 170 });
  
  // Unit Conversions
  doc.setFontSize(12);
  doc.text("Unit Conversions", 20, 65);
  doc.setFontSize(10);
  doc.text("• 1 CFM = 0.000471947443 m³/s", 20, 75);
  doc.text("• 1 HP = 0.745699872 kW", 20, 85);
  doc.text("• 1 in.w.g = 249.088908333 Pa", 20, 95);
  
  // Typical Values
  doc.setFontSize(12);
  doc.text("Typical Values", 20, 115);
  doc.setFontSize(10);
  doc.text("Excellent:", 20, 125);
  doc.text("• < 1.5 kW/(m³/s)", 30, 135);
  doc.text("• < 0.000746 HP/CFM", 30, 145);
  doc.text("Poor:", 20, 155);
  doc.text("• > 2.5 kW/(m³/s)", 30, 165);
  doc.text("• > 0.001243 HP/CFM", 30, 175);
  
  // Footer
  doc.setFontSize(10);
  doc.text("Generated by SPF Calculator - hbradroc@uwo.ca", 20, 280);
  
  // Save the PDF
  doc.save("spf-calculator-results.pdf");
};